### ISSUE TITLE
Missing Python modules

### ISSUE THREAD

**Issue by Jocaru** [allenslab/matrix-dashboard#2]
There are some Python modules that are used that are not installed by default, so maybe you can add a requirements.txt in order to install them automatically.

The ones I found so far:

- numpy
- scipy
- pyowm
- spotipy

Maybe there are more non-default modules that I already had installed.

I also needed to install via apt:

- python3-dateutil
- libatlas-base-dev (in order to get liblapack.so.3, maybe there's another way to install it?

**Comment by TheBasedDoge** [comment]
I installed all those but It still won't run 

`
/home/pi/matrix-dashboard/impl/apps_v2/notion_v2.py:193: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if res.status_code is not 200:
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/matrix-dashboard/impl/controller_v3.py", line 10, in <module>
    from apps_v2 import main_screen, notion_v2, subcount, gif_viewer, weather, life, spotify_player
  File "/home/pi/matrix-dashboard/impl/apps_v2/life.py", line 7, in <module>
    from scipy.signal import convolve2d
  File "/home/pi/.local/lib/python3.9/site-packages/scipy/signal/__init__.py", line 309, in <module>
    from . import _sigtools, windows
ImportError: numpy.core.multiarray failed to import
`

Am I still missing some modules?

**Comment by Rosado2487** [comment]
> I installed all those but It still won't run
> 
> `/home/pi/matrix-dashboard/impl/apps_v2/notion_v2.py:193: SyntaxWarning: "is not" with a literal. Did you mean "!="? if res.status_code is not 200: RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd Traceback (most recent call last): File "/home/pi/matrix-dashboard/impl/controller_v3.py", line 10, in <module> from apps_v2 import main_screen, notion_v2, subcount, gif_viewer, weather, life, spotify_player File "/home/pi/matrix-dashboard/impl/apps_v2/life.py", line 7, in <module> from scipy.signal import convolve2d File "/home/pi/.local/lib/python3.9/site-packages/scipy/signal/__init__.py", line 309, in <module> from . import _sigtools, windows ImportError: numpy.core.multiarray failed to import`
> 
> Am I still missing some modules?
> 
> Edit, i ran pip install numpy --upgrade
> 
> and now I get this `/home/pi/matrix-dashboard/impl/modules/weather_module.py:11: SyntaxWarning: "is not" with a literal. Did you mean "!="? if config is not None and 'OWM' in config and 'token' in config['OWM'] and config['OWM']['token'] is not "" and 'lat' in config['OWM'] and 'lon' in config['OWM']: Traceback (most recent call last): File "/home/pi/matrix-dashboard/impl/controller_v3.py", line 11, in <module> from modules import weather_module, notification_module, spotify_module File "/home/pi/matrix-dashboard/impl/modules/notification_module.py", line 3, in <module> import websocket ModuleNotFoundError: No module named 'websocket'`

go to those instances in each module and change "is not" to "!=". This worked for me.

**Comment by Rosado2487** [comment]
Does anyone have experience with Spotipy in regards to the Spotify Module? I have added the config to the config file. When I scroll to the page, it freezes. No response at all and can't navigate away. Has anyone got the Spotify part to work, and did you have to make any changes?
